apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fcf5w9vyv-python
  janus-idp.io/tekton: fcf5w9vyv-python
  backstage.io/kubernetes-id: fcf5w9vyv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fcf5w9vyv-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
