apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fcf5w9vyv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fcf5w9vyv-python 
  name: fcf5w9vyv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fcf5w9vyv-python 
